version: '3'
services:
  application:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - "9998:8080"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - jaeger
      - cache
      - worker
    command: uvicorn main:app --host 0.0.0.0 --port 8080

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "5775:5775/udp"
      - "16686:16686"
      -
  cache:
    restart: always
    image: redis:5.0.7
    ports:
      - "6379:6379"
